# Лабораторная работа №1

ФИО:  **указать**   
Группа: **указать**  

Отправлять можно следующими способами (**обязательно указать свое ФИО и группу в каком-либо виде**):
1. Создать **приватный** репозиторий на github, добавить меня по нику (l3lush) в Collaborators (Settings -> Collaborators -> Add people)
2. Отправить заполненный ноутбук мне на почту avmysh@gmail.com, либо m1603956@edu.misis.ru
3. Отправить заполненный ноутбук мне в тг @l3lush. 

**Deadlines**:
- soft -- **02.04.2023 23:59** (за сдачу в пределах этого времени +1 балл в табличку)
- hard -- **начало зачетной недели (ориентировочно июнь 2023)**


**Исходные данные**:
+ Датасет, согласно варианту (смотрим [тут](https://docs.google.com/spreadsheets/d/1TM4EqGhCHA9B35SuIcBqorSI3u4mxs2V02Ujth-eSI4/edit?usp=sharing))

**Что необходимо сделать** (по каждому заданию должна быть приведена хотя бы одна ячейка кода, либо текст, как-то поясняющий ее отсутствие):
1. Вывести первые 5 рядов датасета.
2. Посмотреть количество уникальных элементов в целевой переменной, и посчитать, какое количество наблюдений каждого класса.
3. Вывести основные статистики по датасету.
4. Вывести основную информацию по датасету.
5. Проверить данные на наличие миссингов (NaN).  
6. \*Если есть NaNы, заполнить их по следующей стратегии:
+ Если переменнная непрерывная, то медианным значением.
+ Если категориальная перемернная, заполнить модой.
7. Отобразить зависимость целевой переменной по другой любой переменной. 
8. Посчитать корреляции между признаками (можжно не по всем, если численных переменнных слишком много).
9. Посчитать среднее значение целевой переменной по какому-либо категориальному признаку, если такие есть.
10. Нарисовать гистограмму какого-либо признака.

# 0. Пример импорта данных

In [1]:
import warnings
warnings.filterwarnings("ignore")


from sklearn.datasets import fetch_openml
name_of_dataset = "credit-g"  # название вашего датасета из таблицы
data = fetch_openml(name=name_of_dataset)

In [3]:
data.data  # непорсредственно данные

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,residence_since,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,4.0,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,2.0,real estate,22.0,none,own,1.0,skilled,1.0,none,yes
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,3.0,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,4.0,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,4.0,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,no checking,12.0,existing paid,furniture/equipment,1736.0,<100,4<=X<7,3.0,female div/dep/mar,none,4.0,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes
996,<0,30.0,existing paid,used car,3857.0,<100,1<=X<4,4.0,male div/sep,none,4.0,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes
997,no checking,12.0,existing paid,radio/tv,804.0,<100,>=7,4.0,male single,none,4.0,car,38.0,none,own,1.0,skilled,1.0,none,yes
998,<0,45.0,existing paid,radio/tv,1845.0,<100,1<=X<4,4.0,male single,none,4.0,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes
999,0<=X<200,45.0,critical/other existing credit,used car,4576.0,100<=X<500,unemployed,3.0,male single,none,4.0,car,27.0,none,own,1.0,skilled,1.0,none,yes

In [ ]:
data.target  # целевая переменная

In [ ]:
print(data.DESCR)  # описание датасета

# 1. Ваше решение